/**
 * Generate a Supabase migration that seeds `ohio_schools` from the pre-parsed building
 * JSON files. Output is committed and auto-applied by Lovable on push (no service-role
 * key needed). Re-runnable: uses INSERT ... ON CONFLICT (irn) DO UPDATE.
 *
 *   npx tsx scripts/generate-ohio-seed.ts --dir ".\data\_demo\data\buildings" --year 2024-2025 \
 *     --out ".\supabase\migrations\20260611231000_seed_ohio_schools.sql"
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildOhioRecord, type OhioRecord } from './ohioBuildingRecord';

function parseArgs(argv: string[]) {
  const out: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) { out[argv[i].slice(2)] = argv[i + 1]; i++; }
  }
  return out;
}
const args = parseArgs(process.argv.slice(2));
const DIR = args.dir;
const YEAR = args.year || '2024-2025';
const OUT = args.out;
if (!DIR || !OUT) {
  console.error('Usage: --dir <buildings dir> --out <migration .sql path> [--year 2024-2025]');
  process.exit(1);
}

const sqlStr = (v: string | null): string =>
  v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const sqlNum = (v: number | null): string =>
  v === null || v === undefined || Number.isNaN(v) ? 'NULL' : String(v);
const sqlJson = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const COLS = [
  'irn', 'building_name', 'district_name', 'district_irn', 'county', 'city', 'address',
  'low_grade', 'high_grade', 'school_year', 'total_enrollment', 'enrollment_by_grade',
  'pct_economically_disadvantaged', 'pct_students_with_disabilities',
  'pct_english_learners', 'pct_gifted', 'race_ethnicity',
];

function rowTuple(r: OhioRecord): string {
  return `(${[
    sqlStr(r.irn),
    sqlStr(r.building_name),
    sqlStr(r.district_name),
    sqlStr(r.district_irn),
    sqlStr(r.county),
    sqlStr(r.city),
    sqlStr(r.address),
    sqlStr(r.low_grade),
    sqlStr(r.high_grade),
    sqlStr(r.school_year),
    sqlNum(r.total_enrollment),
    sqlJson(r.enrollment_by_grade),
    sqlNum(r.pct_economically_disadvantaged),
    sqlNum(r.pct_students_with_disabilities),
    sqlNum(r.pct_english_learners),
    sqlNum(r.pct_gifted),
    sqlJson(r.race_ethnicity),
  ].join(', ')})`;
}

const records: OhioRecord[] = [];
for (const f of readdirSync(DIR).filter((f) => f.endsWith('.json'))) {
  try {
    const b = JSON.parse(readFileSync(join(DIR, f), 'utf8'));
    if (b?.irn) records.push(buildOhioRecord(b, YEAR).record);
  } catch (e) {
    console.warn(`skip ${f}: ${(e as Error).message}`);
  }
}
records.sort((a, b) => a.irn.localeCompare(b.irn));

const updateClause = COLS.filter((c) => c !== 'irn')
  .map((c) => `${c} = EXCLUDED.${c}`)
  .concat('updated_at = now()')
  .join(',\n    ');

const CHUNK = 200;
const parts: string[] = [
  `-- Seed ohio_schools with the ${YEAR} Ohio School Report Card (${records.length} buildings).`,
  `-- Generated by scripts/generate-ohio-seed.ts from pre-parsed building JSON.`,
  `-- Idempotent: re-running updates existing rows by IRN.`,
  '',
];

for (let i = 0; i < records.length; i += CHUNK) {
  const chunk = records.slice(i, i + CHUNK);
  parts.push(
    `INSERT INTO public.ohio_schools (${COLS.join(', ')}) VALUES`,
    chunk.map(rowTuple).join(',\n'),
    `ON CONFLICT (irn) DO UPDATE SET\n    ${updateClause};`,
    ''
  );
}

const sql = parts.join('\n');
writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`  ${records.length} schools, ${Math.ceil(records.length / CHUNK)} INSERT batches, ${(sql.length / 1_048_576).toFixed(2)} MB`);
